### ISSUE TITLE
GPflow.tfops is not copied by python setup.py install

### ISSUE THREAD

**Issue by fujiisoup** [GPflow/GPflow#192]
Hi all.

`python setup.py install` seems to fail in copying `GPflow/tfops` directory to `build`.
`python setup.py develop` does work.

To reproduce this issue,
+ Delete `build` dir
+ Execute `python setup.py install`
+ Test `python testing/test_transforms.py`

If once `python setup.py develop` is executed, `GPflow/tfops` is copied to `build`, 
then it works even after the `python setup.py install`.

**Comment by fujiisoup** [comment]
> If once python setup.py develop is executed, GPflow/tfops is copied to build,  
> then it works even after the python setup.py install.

This observation was wrong.
Once `build` was removed, `python setup.py install` always fails to copy this directory.

Although codeship is working with this command, I guess it uses old *.so file that was generated at some point...

**Comment by jameshensman** [comment]
Hmm, I don't understand why this should be the case. Codeship starts with a fresh (virtual) machine each time. It also works on readthedocs.io

On my machine, running 
`python setup.py build`

reports
`copying GPflow/tfops/matpackops.so -> build/lib/GPflow/tfops`

does it do the same on yours?

**Comment by fujiisoup** [comment]
Hi @jameshensman 

In my machines, no.  
> `python setup.py build` 

does NOT report  
> `copying GPflow/tfops/matpackops.so -> build/lib/GPflow/tfops`

I also checked Codeship log, it did not either report  
`copying GPflow/tfops/matpackops.so -> build/lib/GPflow/tfops`  
after `python setup.py install` command.

See -> [https://codeship.com/projects/147609/builds/17861246](https://codeship.com/projects/147609/builds/17861246)  
(I did not believe it. But actually, I found this issue when creating a CI env. on Codeship for another project that uses GPflow)

I use setuptools version 25.0.0 on python3.5 (conda virtual env.)

**Comment by fujiisoup** [comment]
I constructed my own codeship environment and let it check my GPflow-fork.
I carried out the following observations.

+ > Codeship starts with a fresh (virtual) machine each time.   
was true (my guess was wrong.)

However,
+ `ls build/lib/GPflow` says  there are not `tfops` dir even after `python setup.py install` command,
which is the same with my machine.

However again
+ `nosetests testing --nologcapture --with-coverage --cover-package=GPflow --cover-erase
` works fine on codeship.

I tried the followings on the codeship,
+ `cp testing/test_transforms.py ./`  
`python test_transforms.py`  
It also works fine,

However, the below fails
+ `python testing/test_transforms.py`

saying   
> tensorflow.python.framework.errors.NotFoundError: /home/rof/miniconda/envs/condaenv/lib/python2.7/site-packages/GPflow-0.3.0-py2.7.egg/GPflow/tfops/matpackops.so: cannot open shared object file: No such file or directory


From the observations, I guess, because test performs from the root directory of GPflow, 
it can see `GPflow/tfopts/matpackops.so` file (not in `build/lib/GPflow` dir).
However, since this file is not registered by `setup` command, 
test fails from the outside of the GPflow root directory.

My conclusion is 
+ Tests is running correctly on the codeship.
+ `setup.py` should be improved to deal with various platforms.

I confirmed the PR#193 works all the above commands on codeship and my machine.

**Comment by fujiisoup** [comment]
I still have a trouble in `python setup install` for the current master.
For the current version, `GPflow/tfops` is successfully copied, but `GPflow/gpflowrc` is not copied to `build` dir.

I think an additional line `include GPflow/gpflowrc` in `MANIFEST.in` seems to solve my problem.  
Is it possible to modify this file?

**Comment by markvdw** [comment]
@fujiisoup, what is your system like? This has been bothering me (silently) for a while, as I can't replicate it!

I'm not that well versed in the distribution tools of Python projects, but from the docs it looks like `MANIFEST.in` may be the right place to change something. @jameshensman, what do you think?

**Comment by fujiisoup** [comment]
Hi @markvdw. Thank you for your reply.

I use Ubuntu 16.04 with conda environment Python 2.7 (laptop) and 3.5 (desktop).

**Comment by jameshensman** [comment]
It's also worried me for a while, for the same reason. I've been reluctant to fix because I don't want to bodge the install without understanding what I'm doing. However, I might never completely understand python packaging :(

MANIFEST.in is the right place for it, yes. 

I don't understand fully why we're not seeing the issue elsewhere though, such as on readthedocs where the install is performed fully.

**Comment by fujiisoup** [comment]
Hi @jameshensman 

Also in my environment, the nosetests works fine even if there is no gpflowrc file in build dir.
However, `python testing/test_param.py` fails.

I think the test works because it sees gpflowrc file in GPflow/GPflow dir.

**Comment by fujiisoup** [comment]
solved by #233

**Comment by 1Reinier** [comment]
I still have this issue with GPflow 0.3.5 and TensorFlow 1.0.0. What can I do to circumvent this issue?

Upon 
```python
import GPflow
```
 I get this error:

```python-traceback
---------------------------------------------------------------------------
NotFoundError                             Traceback (most recent call last)
<ipython-input-1-47b2465465ad> in <module>()
      5 import matplotlib.pyplot as plt
      6 
----> 7 import GPflow

/home/anaconda3/envs/lib/python3.5/site-packages/GPflow-0.3.5-py3.5.egg/GPflow/__init__.py in <module>()
     16 # flake8: noqa
     17 from __future__ import absolute_import
---> 18 from . import (likelihoods, kernels, ekernels, param, model, gpmc, sgpmc, priors, gpr, svgp, vgp, sgpr, gplvm, tf_wraps,
     19                tf_hacks)
     20 from ._version import __version__

/home/anaconda3/envs/lib/python3.5/site-packages/GPflow-0.3.5-py3.5.egg/GPflow/likelihoods.py in <module>()
     15 
     16 from __future__ import absolute_import
---> 17 from . import densities, transforms
     18 import tensorflow as tf
     19 import numpy as np

/home/anaconda3/envs/lib/python3.5/site-packages/GPflow-0.3.5-py3.5.egg/GPflow/transforms.py in <module>()
     16 import numpy as np
     17 import tensorflow as tf
---> 18 from . import tf_wraps as tfw
     19 from ._settings import settings
     20 

/home/anaconda3/envs/lib/python3.5/site-packages/GPflow-0.3.5-py3.5.egg/GPflow/tf_wraps.py in <module>()
     34 
     35 
---> 36 _custom_op_module = tf.load_op_library(os.path.join(os.path.dirname(__file__), 'tfops', 'matpackops.so'))
     37 vec_to_tri = _custom_op_module.vec_to_tri
     38 tri_to_vec = _custom_op_module.tri_to_vec

/home/anaconda3/envs/lib/python3.5/site-packages/tensorflow-1.0.0-py3.5-linux-x86_64.egg/tensorflow/python/framework/load_library.py in load_op_library(library_filename)
     62       # pylint: disable=protected-access
     63       raise errors_impl._make_specific_exception(
---> 64           None, None, error_msg, error_code)
     65       # pylint: enable=protected-access
     66   finally:

NotFoundError: /home/anaconda3/envs/lib/python3.5/site-packages/GPflow-0.3.5-py3.5.egg/GPflow/tfops/matpackops.so: cannot open shared object file: No such file or directory
```

And during `python setup.py build` I get:

```zsh
./GPflow/tfops/vec_to_tri.cc:16:42: fatal error: tensorflow/core/framework/op.h: No such file or directory
compilation terminated.
GPflow/tfops/tri_to_vec.cc:16:42: fatal error: tensorflow/core/framework/op.h: No such file or directory
```
Any ideas?

**Comment by 1Reinier** [comment]
Got it resolved. I built Tensorflow from scratch with gcc5 so I had to remove the flag in setup.py.

**Comment by AAbusnina** [comment]
Can anyone elaborate how to solve this problm? I have installed TensorFlow and it works fine, but GPflow still throws the eerror: "site-packages\GPflow\GPflow\tfops\matpackops.so not found"
